"""Added arrays table

Revision ID: a71a53f9ee25
Revises:
Create Date: 2021-07-19 21:26:36.361758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a71a53f9ee25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrays',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('in_arr', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('out_arr', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='arrays_pkey')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arrays')
    # ### end Alembic commands ###
